# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-14 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191213_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
