# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 22:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('like', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ParentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contentshared',
            name='host_user',
        ),
        migrations.RemoveField(
            model_name='contentshared',
            name='users_shared',
        ),
        migrations.DeleteModel(
            name='ContentShared',
        ),
    ]
