# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-11 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191210_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='content',
            name='commentLikesDisabled',
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='content_meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='v_content_data', to='content.Content'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='content_meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='t_content_data', to='content.Content'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_content_data', to='content.Content'),
        ),
    ]
